### ISSUE TITLE
Uncaught Channel closed

### ISSUE THREAD

**Issue by ananthasharma** [mulesoft/aml-workbench#1]
[Enter steps to reproduce:]

1. install Atom on MacOS 
2. install api-workbench
3. create a RAML project
4. try to edit some .raml file

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [aml-workbench](https://github.com/mulesoft/aml-workbench) package 0.0.19

### Stack Trace

Uncaught Channel closed

```
At events.js:167

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:627:16)
    at NodeProcessClientConnection.sendMessage (/packages/aml-workbench/node_modules/api-language-server/dist/entryPoints/node/client/client.js:38:28)
    at NodeProcessClientConnection.MessageDispatcher.send (/packages/aml-workbench/node_modules/api-language-server/dist/entryPoints/common/messageDispatcher.js:26:14)
    at NodeProcessClientConnection.AbstractClientConnection.positionChanged (/packages/aml-workbench/node_modules/api-language-server/dist/entryPoints/common/client/abstractClient.js:387:14)
    at t.cursorChanged (/packages/aml-workbench/main.js:1:3128)
    at /packages/aml-workbench/main.js:1:2569
    at Function.simpleDispatch (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at TextEditor.cursorMoved (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:547080)
    at Selection.marker.onDidChange.e (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:532223)
    at Function.simpleDispatch (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at DisplayMarker.notifyObservers (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2855767)
    at /private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2851269
    at Function.simpleDispatch (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at Marker.emitChangeEvent (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:14:73563)
    at Marker.update (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:14:72617)
    at Marker.setHeadPosition (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:14:68776)
    at DisplayMarker.setHeadBufferPosition (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2853122)
    at DisplayMarker.setHeadScreenPosition (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2853354)
    at changePosition (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:522245)
    at Cursor.changePosition (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:530789)
    at Cursor.setScreenPosition (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:522211)
    at moveCursors.o (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:30282)
    at Array.forEach (<anonymous>)
    at transact (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:33144)
    at TextBuffer.transact (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:492111)
    at TextEditor.transact (/private/var/folders/lr/34hntbl92_77j1xm73mqctjm0000gn/T/AppTranslocation/3F1A7261-BCF2-4406-9224-24D3B8D761E8/d/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
```

### Commands

```
     -1:57.9.0 core:confirm (input.hidden-input)
 20x -1:57.3.0 core:backspace (input.hidden-input)
  5x -1:46.4.0 core:move-down (input.hidden-input)
  3x -1:45.4.0 core:move-up (input.hidden-input)
  6x -1:43.8.0 core:move-down (input.hidden-input)
 12x -1:41 core:move-up (input.hidden-input)
  5x -1:38.5.0 core:move-down (input.hidden-input)
     -1:33.2.0 core:move-up (input.hidden-input)
 25x -1:32.7.0 core:move-down (input.hidden-input)
     -1:16.7.0 core:select-all (input.hidden-input)
  6x -1:13.8.0 core:backspace (input.hidden-input)
     -1:08.4.0 core:select-all (input.hidden-input)
     -1:08.3.0 core:backspace (input.hidden-input)
     -1:07.8.0 editor:consolidate-selections (input.hidden-input)
     -1:07.8.0 core:cancel (input.hidden-input)
  3x -0:47 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
aml-workbench 0.0.19 
api-workbench 0.8.48 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.7.1 
```

**Comment by jarrodek** [comment]
I have the same issue happening all the time when editing a RAML file.
